Repository TEAM-3V3R/AI, pull requests merged in 2025-04, with the labels that each got.

#6 feat: 문맥 기반 의미 추론 추가 #5
  main.py
Labels: feat

#8 [add] 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
Labels: add

#10 [Test] spring 연동 : 프롬프트 #5
  .gitignore
  main.py
Labels: test
